/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as GeneratorIndexRouteImport } from './routes/generator/index'
import { Route as PassportIndexRouteImport } from './routes/passport/index'
import { Route as PassportScanRouteImport } from './routes/passport/scan'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorIndexRoute = GeneratorIndexRouteImport.update({
  id: '/generator/',
  path: '/generator/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportIndexRoute = PassportIndexRouteImport.update({
  id: '/passport/',
  path: '/passport/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportScanRoute = PassportScanRouteImport.update({
  id: '/passport/scan',
  path: '/passport/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/passport/scan': typeof PassportScanRoute
  '/collection/': typeof CollectionIndexRoute
  '/generator/': typeof GeneratorIndexRoute
  '/passport/': typeof PassportIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/passport/scan': typeof PassportScanRoute
  '/collection': typeof CollectionIndexRoute
  '/generator': typeof GeneratorIndexRoute
  '/passport': typeof PassportIndexRoute
  '/studio': typeof StudioIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/passport/scan': typeof PassportScanRoute
  '/collection/': typeof CollectionIndexRoute
  '/generator/': typeof GeneratorIndexRoute
  '/passport/': typeof PassportIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/passport/scan'
    | '/collection/'
    | '/generator/'
    | '/passport/'
    | '/studio/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/passport/scan'
    | '/collection'
    | '/generator'
    | '/passport'
    | '/studio'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/passport/scan'
    | '/collection/'
    | '/generator/'
    | '/passport/'
    | '/studio/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PassportScanRoute: typeof PassportScanRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  GeneratorIndexRoute: typeof GeneratorIndexRoute
  PassportIndexRoute: typeof PassportIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator/': {
      id: '/generator/'
      path: '/generator'
      fullPath: '/generator/'
      preLoaderRoute: typeof GeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/': {
      id: '/passport/'
      path: '/passport'
      fullPath: '/passport/'
      preLoaderRoute: typeof PassportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/scan': {
      id: '/passport/scan'
      path: '/passport/scan'
      fullPath: '/passport/scan'
      preLoaderRoute: typeof PassportScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PassportScanRoute: PassportScanRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  GeneratorIndexRoute: GeneratorIndexRoute,
  PassportIndexRoute: PassportIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
